module miter (
	input logic[31:0] address_1,
	input logic[31:0] address_2,
	output logic busy_o_1,
	output logic busy_o_2,
	input logic clk,
	input logic[15:0][31:0] cptra_csr_hmac_key_1,
	input logic[15:0][31:0] cptra_csr_hmac_key_2,
	input logic cptra_pwrgood_1,
	input logic cptra_pwrgood_2,
	input logic cs_1,
	input logic cs_2,
	input logic debugUnlock_or_scan_mode_switch_1,
	input logic debugUnlock_or_scan_mode_switch_2,
	output logic error_intr_1,
	output logic error_intr_2,
	input kv_defines_pkg::kv_rd_resp_t[1:0] kv_rd_resp_1,
	input kv_defines_pkg::kv_rd_resp_t[1:0] kv_rd_resp_2,
	output kv_defines_pkg::kv_read_t[1:0] kv_read_1,
	output kv_defines_pkg::kv_read_t[1:0] kv_read_2,
	input kv_defines_pkg::kv_wr_resp_t kv_wr_resp_1,
	input kv_defines_pkg::kv_wr_resp_t kv_wr_resp_2,
	output kv_defines_pkg::kv_write_t kv_write_1,
	output kv_defines_pkg::kv_write_t kv_write_2,
	output logic notif_intr_1,
	output logic notif_intr_2,
	output logic[31:0] read_data_1,
	output logic[31:0] read_data_2,
	input logic reset_n,
	input logic we_1,
	input logic we_2,
	input logic[31:0] write_data_1,
	input logic[31:0] write_data_2
);

	hmac DUV1(
		.address(address_1),
		.busy_o(busy_o_1),
		.clk(clk),
		.cptra_csr_hmac_key(cptra_csr_hmac_key_1),
		.cptra_pwrgood(cptra_pwrgood_1),
		.cs(cs_1),
		.debugUnlock_or_scan_mode_switch(debugUnlock_or_scan_mode_switch_1),
		.error_intr(error_intr_1),
		.kv_rd_resp(kv_rd_resp_1),
		.kv_read(kv_read_1),
		.kv_wr_resp(kv_wr_resp_1),
		.kv_write(kv_write_1),
		.notif_intr(notif_intr_1),
		.read_data(read_data_1),
		.reset_n(reset_n),
		.we(we_1),
		.write_data(write_data_1)
	);

	hmac DUV2(
		.address(address_2),
		.busy_o(busy_o_2),
		.clk(clk),
		.cptra_csr_hmac_key(cptra_csr_hmac_key_2),
		.cptra_pwrgood(cptra_pwrgood_2),
		.cs(cs_2),
		.debugUnlock_or_scan_mode_switch(debugUnlock_or_scan_mode_switch_2),
		.error_intr(error_intr_2),
		.kv_rd_resp(kv_rd_resp_2),
		.kv_read(kv_read_2),
		.kv_wr_resp(kv_wr_resp_2),
		.kv_write(kv_write_2),
		.notif_intr(notif_intr_2),
		.read_data(read_data_2),
		.reset_n(reset_n),
		.we(we_2),
		.write_data(write_data_2)
	);

endmodule
